name: doceria_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  intl: ^0.18.1
  go_router: ^16.0.0
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.0.0+2
  curved_navigation_bar: ^1.0.6
  carousel_slider: ^5.1.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/images/produtos/
    - asset/images/apresentacao/

  fonts:
    - family: league_gothic
      fonts:
        - asset: asset/fonts/leagueGothic/LeagueGothic-Regular.ttf
    #         style: italic
    - family: Dongle
      fonts:
        - asset: asset/fonts/Dongle/Dongle-Regular.ttf
        - asset: asset/fonts/Dongle/Dongle-Bold.ttf
          weight: 700
        - asset: asset/fonts/Dongle/Dongle-Light.ttf
          weight: 300
